services:
    redis-db:
        image: 'redis'
        volumes:
            - ./redis:/usr/app
        command: ["redis-server", "--save", "1 1", "--protected-mode", "no"]
    node-app:
        build: ./
        image: 'docker.io/avijain1502/visits'
        ports:
            - "8081:8081"   